language: node_js

node_js:
  - "0.10.28"


before_install:
  - npm install -g npm

install:
  # install required dependencies
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

script:
  - gulp build
  - gulp build-specs